# vim:fileencoding=utf-8:foldmethod=marker

# Font settings
font_family      Maple Mono NF
bold_font        Maple Mono NF Bold
italic_font      Maple Mono NF Italic
bold_italic_font Maple Mono NF Bold Italic
font_size 18.0
adjust_line_height 115%

# Cursor
cursor_blink_interval 0

# Window
hide_window_decorations titlebar-only
window_padding_width 15

# Misc
macos_option_as_alt yes
text_composition_strategy legacy
# macos_thicken_font 0.1

# Theme
include onechaco.conf
keyboard_layout es

# Colors These values too can be used default, displayp3, srgb (browser colors)
macos_colorspace displayp3

# Glossy Background
background_opacity 0.8
background_blur 55

# Disable option key for kitty
map modifier none Option

# Adding font features
font_features MapleMono-NF-Regular +ss01 +cv03
font_features MapleMono-NF-Bold +ss01 +cv03
font_features MapleMono-NF-Italic +ss01 +cv03
font_features MapleMono-NF-BoldItalic +ss01 +cv03
